[build]
  command = "npm install"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = ["primes/**", "fivesim.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
